---
# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "soft"

# Shrink default JVM heap.
esJavaOpts: "-Xmx2g -Xms2g"

nameOverride: avib-elastic
fullnameOverride: avib-elastic

replicas: 3

extraEnvs:
  - name: ELASTIC_PASSWORD
    value: password
  - name: ELASTIC_USERNAME
    value: elastic

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: 1
    memory: "4Gi"
  limits:
    memory: "4Gi"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 20Gi
